language: python
python:
    - "3.5"
    
install:
    #------------------
    # Base requirements
    #------------------
    - sudo apt-get update
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    - bash setup_env.sh
    - source activate ps2ff
    #- pip install .
    #- python setup.py install
script:
    - export PYTHONPATH="."
    - py.test --cov=.
after_success:
    - pip install codecov codacy-coverage
    - codecov
    - coverage xml
    - python-codacy-coverage -r coverage.xml
    - bash <(curl -s https://codecov.io/bash)
